### ISSUE TITLE
@EnumMapping Example

### ISSUE THREAD

**Issue by Felipe00** [lets-blade/blade-demos#27]
I'm look in most of folders and not found any references to @EnumMapping. In fact, no documentation inside the class (when you push Documentation's Key(s)). Can you explain me how to use? I'd loved this framework (Newbie detected)

Some code

```
public class User extends Model {

    @EnumMapping(value = "profile")
    enum Profile {
        ADMIN,
        OTHERS
    }

    private Integer id;
    private String name;
    private Profile profile;

   // getters and setters

}
```

Error:

```
java.lang.RuntimeException: io.github.biezhi.anima.exception.AnimaException
	at org.sql2o.Query.converterValue(Query.java:154)
	at org.sql2o.Query.withParams(Query.java:131)
	at io.github.biezhi.anima.core.AnimaQuery.save(AnimaQuery.java:1211)
	at io.github.biezhi.anima.Model.save(Model.java:28)
	at com.ananke.controllers.UsuarioController.saveUser(UserController.java:20)
	at com.ananke.controllers.UsuarioControllerMethodAccess.invoke(Unknown Source)
	at com.blade.reflectasm.MethodAccess.invoke(MethodAccess.java:43)
	at com.blade.server.netty.RouteMethodHandler.routeHandle(RouteMethodHandler.java:256)
	at com.blade.server.netty.RouteMethodHandler.handle(RouteMethodHandler.java:87)
	at com.blade.server.netty.HttpServerHandler.executeLogic(HttpServerHandler.java:158)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.github.biezhi.anima.exception.AnimaException
	at org.sql2o.converters.DefaultEnumConverterFactory$1.toDatabaseParam(DefaultEnumConverterFactory.java:79)
	at org.sql2o.converters.DefaultEnumConverterFactory$1.toDatabaseParam(DefaultEnumConverterFactory.java:49)
	at org.sql2o.Query.converterValue(Query.java:152)
	... 18 more
Caused by: java.lang.NoSuchFieldException: profile
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.sql2o.converters.DefaultEnumConverterFactory$1.toDatabaseParam(DefaultEnumConverterFactory.java:75)
	... 20 more
```

Error occurs because I don't know how to use `@EnumMapping`. I'm doing a POST request to this object and trying to `save()`.

**Comment by Felipe00** [comment]
# [Solved]
I just put @EnumMapping in everywhere to see if works and release that I have to pu upside Model class, like right that:

```
@EnumMapping("profile")
public class User extends Model {

    enum Profile {
        ADMIN,
        OTHERS
    }

    private Integer id;
    private String name;
    private Profile profile;

   // getters and setters

}
```
